spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/trading?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456