spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

page-size: 10

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/trading?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456

---
# 测试环境
spring:
  profiles: test
#  datasource:
#    url: jdbc:mysql://localhost:3306/sars?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
#    username: root
#    password: 123456
  datasource:
    schema: classpath:init_table.sql
    driverClassName: org.h2.Driver

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}